modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="twilightdelight"
version="1.0.1"
displayName="Twilight Delight"
credits="Face the fear,build the food"
displayURL="https://center.mcmod.cn/55994/"
logoFile="logo.png"
authors="Laokuai233"
description='''
More delicious food in the Twilight Forest!
'''

[[dependencies.twilightdelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.twilightdelight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.twilightdelight]]
    modId="twilightforest"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


